name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate snake.svg
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: NkPetrov
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
